### ISSUE TITLE
Add Clear Chat button to index.html

### ISSUE THREAD

**Issue by Drakxard** [Drakxard/copilot#2]
Add a "Clear Chat" button to allow users to clear the chat history. Here are the changes needed:

1. Add the button HTML in the chat container header (after the status indicator):

```html
<div class="status-indicator">
    <div class="status-dot"></div>
    <span id="status-text">Conectando...</span>
</div>
<button id="clear-chat-btn" class="clear-chat-btn">
    🗑️ Borrar Chat
</button>
```

2. Add the CSS styles (add this in the style section):

```css
.clear-chat-btn {
    padding: 8px 16px;
    border: 1px solid rgba(139, 92, 246, 0.3);
    border-radius: 8px;
    background: rgba(139, 92, 246, 0.1);
    color: var(--text-secondary);
    cursor: pointer;
    font-size: 14px;
    transition: all 0.3s ease;
    display: flex;
    align-items: center;
    gap: 6px;
}

.clear-chat-btn:hover {
    background: rgba(139, 92, 246, 0.2);
    color: var(--text-primary);
    transform: translateY(-1px);
}

@media (max-width: 768px) {
    .clear-chat-btn {
        width: 100%;
        justify-content: center;
    }
}
```

3. Add the JavaScript functionality (add in the AdaptiveApp class):

```javascript
initializeElements() {
    // ... existing code ...
    
    // Add clear chat button
    this.clearChatBtn = document.getElementById('clear-chat-btn');
}

attachEventListeners() {
    // ... existing code ...
    
    // Add clear chat functionality
    this.clearChatBtn.addEventListener('click', () => this.clearChat());
}

clearChat() {
    // Remove all messages
    this.chatMessages.innerHTML = '';
    
    // Add back the welcome message
    const welcomeMessage = document.createElement('div');
    welcomeMessage.className = 'welcome-message';
    welcomeMessage.innerHTML = `
        <h2>¡Hola! 👋</h2>
        <p>Soy tu asistente de aprendizaje inteligente.</p>
        <p>Puedo ayudarte con preguntas sobre tus materiales de estudio.</p>
        <p><strong>Prueba preguntando:</strong> "¿Qué es machine learning?" o "Explícame Python"</p>
    `;
    this.chatMessages.appendChild(welcomeMessage);
}
```

These changes will add a clear chat button that:
1. Appears in the header section
2. Has a consistent style with the rest of the UI
3. Is responsive on mobile devices
4. Clears all messages and restores the welcome message when clicked
5. Has a hover effect for better user interaction

The button uses the same color scheme as the rest of the interface and includes a trash can emoji for visual clarity.
